#!/usr/bin/env python3

import os
import time
import serial

ser = serial.Serial('/dev/ttyUSB0')
ser.setRTS(True)
time.sleep(0.1)
ser.setRTS(False)

os.system('rshell -b 115200 -p /dev/ttyUSB0 -f scripts/repl')
